### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Holonist** [LudovicLemaire/AtlasAutoSaver#1]
Hi, I just wanted to say thank you to provide this tool publicly.

I'm a solo player and after building a Schooner for about 8 hours my ship simply got deleted after I died, and I was teleported to a server tile I never visited before. Even with cheats it took about two hours to restore my ship and it didn't feel good to do it. Now I'm running the game with your AutoSaver and it lets me play in peace.

Cheers, Holo

**Comment by LudovicLemaire** [comment]
Thanks for your comment !

Really happy to see people using this tool !
Btw, I made other tools in web format at [globy.dev](https://globy.dev/calcList)

There is Stat Extractor for your animals (to see where they put their points into, usefull for breeding line). It works with used/imprinted animals aswell.

A Breeding Calculator, to know where to breed animals, how much time does it takes, temperatures needed, and a breeding program.

And a Fastest Path Calc (Treasure Hunt Path). You click everywhere you will need to go, with your start point as the first one.
And it will calculate then draw the fastest path to visite all thooses points then come back home.
Usefull when you do lots of treasure maps, or when you need to pass by multiple biomes for differents resources, or even doing Golden Age Island ^^


I wish you safe travel !
Globy
